method: atlasnetv2
data:
  path: data/ShapeNet
  train_split: train # Overfit to train data, see if training is working
  val_split: train
  test_split: train
  classes: ['02691156'] # plane
  img_folder: img_choy2016
  img_size: 224 
  pointcloud_target_n: 4096
  patch_side_length: 20 # will be powered by dim - 1, if dim == 3, then 900
  is_generate_mesh: false
  debug:
    sample_n: 50
model:
  encoder_latent: null
  decoder: atlasnetv2decoder 
  encoder: resnet18
  c_dim: 256
  z_dim: 0
  decoder_kwargs:
    npatch: 10
    patchDim: 2
    patchDeformDim: 3
    hidden_size: 256
training:
  out_dir:  out/img/debug_atlasnetv2
  batch_size: 20
  val_batch_size: 2
  model_selection_metric: cd1
  model_selection_mode: maximize
  visualize_every: 500
  validate_every: 1000
  checkpoint_every: 100000
  skip_load_pretrained_optimizer: false
  learning_rate: 1e-3
  learning_rage_decay_at:
    - 250
    - 300
trainer:
  point_scale: 2
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

