inherit_from: configs/img/pnet.yaml
data:
  classes: ['02691156'] # plane
  train_split: train # Overfit to train data, see if training is working
  val_split: train
  test_split: train
  is_normal_icosahedron: false
  icosahedron_subdiv: 2
  icosahedron_uv_margin: 0.00001
  uv_sphere_length: 20
  debug:
    sample_n: 50
model:
  decoder_kwargs:
    n_primitives: 10
    paramnet_class: ParamNet
    shape_sampler_decoder_class: PrimitiveWiseGroupConvDecoder
    #shape_sampler_decoder_class: PrimitiveWiseGroupConvDecoderUseFCToExpandFeature
    #shape_sampler_decoder_class: BatchNormDecoder
    is_train_periodic_shape_sampler: true
training:
  out_dir:  out/img/test_dataparallel
  batch_size: 10
  visualize_every: 100
  validate_every: 1000
  checkpoint_every: 2
  wandb_resume: null
  skip_load_pretrained_optimizer: false
  learning_rate: 1e-4
trainer:
  add_pointcloud_occ: false
  is_normal_loss: false
  normal_loss_coef: 10

