method: pnet
data:
  dataset: Shapes3D
  path: data/ShapeNet
  classes: null
  input_type: img
  train_split: train
  val_split: val
  test_split: test
  dim: 3
  sdf_points_file: sdf_points.npz
  points_file: points.npz
  points_iou_file: points.npz
  points_subsample: 2048
  points_unpackbits: true
  model_file: model.off
  watertight_file: model_watertight.off
  img_folder: img_choy2016
  img_size: 224
  img_with_camera: false
  img_augment: false
  n_views: 24
  pointcloud_file: pointcloud.npz
  pointcloud_chamfer_file: pointcloud.npz
  pointcloud_n: 256
  pointcloud_target_n: 4096
  pointcloud_noise: 0.05
  voxels_file: model.binvox
  with_transforms: false
  primitive_points_sample_n: 20
  is_normal_icosahedron: false
  icosahedron_subdiv: 2
  icosahedron_uv_margin: 1.0e-05
  uv_sphere_length: 20
  normal_mesh_no_invert: false
model:
  decoder: simplest
  encoder: resnet18
  encoder_latent: null
  decoder_kwargs:
    max_m: 0
    n_primitives: 10
    is_train_periodic_shape_sampler: true
    is_quadrics: false
    is_sphere: true
    shape_sampler_decoder_factor: 1
    transition_range: 3
    shape_sampler_decoder_class: PrimitiveWiseGroupConvDecoder
    paramnet_class: ParamNet
    paramnet_dense: true
    is_feature_radius: false
    is_feature_coord: true
    is_feature_angles: false
    disable_learn_pose_but_transition: true
  encoder_kwargs: {}
  encoder_latent_kwargs: {}
  multi_gpu: false
  c_dim: 256
  z_dim: 0
  use_camera: false
  dmc_weight_prior: 10.0
training:
  out_dir: out/img/pnet_finetue_only_transition_cceff10_pn10_target_n_4096_no_overlap_reg_finetune_no_reg_normal_ceof1
  batch_size: 20
  val_batch_size: 2
  vis_batch_size: 5
  print_every: 10
  visualize_every: 1000
  checkpoint_every: 10000
  validate_every: 2500
  backup_every: 100000
  eval_sample: false
  model_selection_metric: iou
  model_selection_mode: maximize
  wandb_resume: null
  skip_load_pretrained_optimizer: false
  learning_rate: 1e-4
  is_onet_style_occ_loss: false
test:
  threshold: 0.7999999999999998
  eval_mesh: true
  eval_pointcloud: false
  eval_fscore: true
  fscore_thresholds:
  - 0.005053668503213957
  - 0.0107337006427915
  - 0.02021467401285583
  - 0.050536685032139574
  - 0.10107337006427915
  - 0.2021467401285583
  model_file: model_best.pt
  model_file_hash: 0887b7818b1d240919eb9d8b3463b2d5
generation:
  batch_size: 100000
  refinement_step: 0
  vis_n_outputs: 30
  generate_mesh: true
  generate_pointcloud: true
  generation_dir: generation
  use_sampling: false
  resolution_0: 32
  upsampling_steps: 2
  simplify_nfaces: null
  copy_groundtruth: false
  copy_input: true
  latent_number: 4
  latent_H: 8
  latent_W: 8
  latent_ny: 2
  latent_nx: 2
  latent_repeat: true
  refine: false
  n_x: 128
  n_z: 1
preprocessor:
  type: null
  config: ''
  model_file: null
trainer:
  chamfer_loss_coef: 10
  is_normal_loss: false
  occupancy_loss_coef: 1
  overlap_reg_coef: 0
  overlap_reg_threshold: 1.2
  pnet_point_scale: 6
  self_overlap_reg_coef: 0
  self_overlap_reg_threshold: 0.1
  normal_loss_coef: 1
  is_get_radius_direction_as_normals: true
