method: pnet
data:
  path: data/ShapeNet
  img_folder: img_choy2016
  img_size: 224 
  points_subsample: 2048 
  pointcloud_target_n: 4096
  primitive_points_sample_n: 20 # will be powered by dim - 1, if dim == 3, then 900
  is_normal_icosahedron: false
  icosahedron_subdiv: 2
  icosahedron_uv_margin: 0.00001
  uv_sphere_length: 20
  normal_mesh_no_invert: false
model:
  encoder_latent: null
  decoder: simplest
  encoder: resnet18
  c_dim: 256
  z_dim: 0
  decoder_kwargs:
    max_m: 0
    n_primitives: 30
    is_train_periodic_shape_sampler: true
    is_quadrics: false
    is_sphere: true
    shape_sampler_decoder_factor: 1
    transition_range: 3
    shape_sampler_decoder_class: PrimitiveWiseGroupConvDecoder #ShapeDecoderCBatchNorm
    paramnet_class: ParamNet
    paramnet_dense: true
    is_feature_radius: false
    is_feature_coord: true
    is_feature_angles: false
    is_shape_sampler_sphere: false
    disable_learn_pose_but_transition: true
trainer:
  overlap_reg_coef: 0
  self_overlap_reg_coef: 0
  occupancy_loss_coef: 1
  chamfer_loss_coef: 10
  pnet_point_scale: 6 #periodic net works well if point scale is multiplied by 6
  overlap_reg_threshold: 1.2
  self_overlap_reg_threshold: 0.1
  is_normal_loss: false
  normal_loss_coef: 3
  is_logits_by_min: true
  is_sdf: true
training:
  out_dir:  out/img/pnet_finetue_only_transition_cceff10_pn30_no_regs_no_normal_sdf
  batch_size: 20
  val_batch_size: 2
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 1000
  validate_every: 2500
  checkpoint_every: 10000
  skip_load_pretrained_optimizer: false
  learning_rate: 1e-4
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

