method: pnet
data:
  path: data/ShapeNet
  input_type: idx
  classes:
    - 02691156
  train_split: test
  test_split: test
  val_split: test
  points_subsample: 4096
  pointcloud_target_n: 4096
  primitive_points_sample_n: 10 # will be powered by dim - 1, if dim == 3, then 900
  is_normal_icosahedron: true
  icosahedron_subdiv: 3
  icosahedron_uv_margin: 0.00001
  uv_sphere_length: 20
  normal_mesh_no_invert: false
  debug:
    sample_n: 1
    train_shuffle: false

model:
  encoder_latent: simple
  decoder: simplest
  encoder: idx
  c_dim: 1
  z_dim: 0
  decoder_kwargs:
    max_m: 0
    n_primitives: 12
    is_train_periodic_shape_sampler: false
    is_quadrics: false
    is_sphere: true
    shape_sampler_decoder_factor: 2
    transition_range: 3
    shape_sampler_decoder_class: PrimitiveWiseGroupConvDecoder
    paramnet_class: ParamNet
    paramnet_dense: true
    is_feature_radius: false
    is_feature_coord: true
    is_feature_angles: false
    disable_learn_pose_but_transition: true
trainer:
  overlap_reg_coef: 1
  self_overlap_reg_coef: 1
  occupancy_loss_coef: 1
  chamfer_loss_coef: 10
  pnet_point_scale: 6 #periodic net works well if point scale is multiplied by 6
  overlap_reg_threshold: 1.2
  self_overlap_reg_threshold: 0.1
  is_normal_loss: true
  normal_loss_coef: 3
training:
  out_dir:  out/overfit/pnet
  batch_size: 1
  val_batch_size: 1
  model_selection_metric: iou
  model_selection_mode: maximize
  visualize_every: 100
  validate_every: 1000
  checkpoint_every: 10000
  skip_load_pretrained_optimizer: false
  learning_rate: 1e-2
test:
  threshold: 0.5
  eval_mesh: true
  eval_pointcloud: false
generation:
  batch_size: 100000
  refine: false
  n_x: 128
  n_z: 1
  resolution_0: 32 
  upsampling_steps: 2

